### ISSUE TITLE
Configuration error when building etherlab.

### ISSUE THREAD

**Issue by stefanpoeter** [Beckhoff/CX9020#7]
So far everything is fine, except when I build the etherlab module.
```
configure: error: Failed to extract Linux kernel version!
Makefile:9: die Regel für Ziel „etherlab“ scheiterte
make: *** [etherlab] Fehler 1
````

**Comment by pbruenn** [comment]
Did you compile the kernel completely before you run etherlab?
What kind of host environment do you use to build?

**Comment by stefanpoeter** [comment]
I did, as it says:

```
#get and patch a rt kernel:
#==========================
./tools/prepare_kernel.sh 4.4.27-rt37

#configure and build the kernel:
#===============================
make kernel
```

No errors after compiling the kernel.

I use ubuntu 16.04 with kernel 4.4.0-45-generic.

**Comment by pbruenn** [comment]
If the kernel build finished before you start the etherlab build and you still have that error, I have no further idea. It is important, that the kernel build completed before the etherlab configuration begins, because etherlab depends on some kernel headers.

You could try an etherlab installation from scratch:
http://etherlab.org/download/ethercat/ethercat-1.5.2.pdf
or post your complete build output, to see if there is something else.

**Comment by stefanpoeter** [comment]
I probably forgot to specify the kernel on the prepare_kernel script. It is working now.

Thanks for your help.
